# SPDX-FileCopyrightText: 2023 DE:AD:10:C5 <https://github.com/DEAD10C5/>
#
# SPDX-License-Identifier: CC0-1.0

name: markdown
on:
  pull_request:
    branches: [ main ]
jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v3.5.0
      with:
        files: .
        config_file: ".markdownlint.json"

